/**
 * Seeds a complete, presentation-ready dataset.
 *
 *   npm run seed:demo            add demo data, skipping anything that exists
 *   npm run seed:demo -- --reset wipe ALL claims/policies/hospitals/notifications
 *                                /audit logs and demo users first, then reseed
 *
 * The claims below are deliberately engineered so that each fraud risk tier
 * (low / medium / high) and several validation failures are represented, which
 * makes the officer review screen meaningful without any manual data entry.
 */
require("dotenv").config();

const fs = require("fs");
const path = require("path");
const bcrypt = require("bcryptjs");
const mongoose = require("mongoose");

const connectDB = require("../config/db");
const User = require("../models/User");
const Hospital = require("../models/Hospital");
const Policy = require("../models/Policy");
const Claim = require("../models/Claim");
const ClaimDocument = require("../models/ClaimDocument");
const FraudScore = require("../models/FraudScore");
const ApprovalRecord = require("../models/ApprovalRecord");
const Notification = require("../models/Notification");
const AuditLog = require("../models/AuditLog");
const { processSubmittedClaim } = require("../services/claimProcessing");
const { notifyUser } = require("../services/notificationService");
const { createAuditLog } = require("../services/auditService");
const { uploadDir } = require("../middleware/uploadMiddleware");

const RESET = process.argv.includes("--reset");

const PASSWORDS = {
  admin: "Admin123!",
  officer: "Officer123!",
  hospital: "Hospital123!",
  member: "Member123!",
};

const DEMO_USERS = [
  { key: "admin", name: "System Admin", email: "admin@shi.local", role: "admin", password: PASSWORDS.admin },
  { key: "officer", name: "Sana Officer", email: "officer@shi.local", role: "officer", password: PASSWORDS.officer },
  { key: "hospitalStaff", name: "City General Hospital", email: "hospital@shi.local", role: "hospital", password: PASSWORDS.hospital },
  { key: "ayesha", name: "Ayesha Khan", email: "ayesha@shi.local", role: "policyholder", password: PASSWORDS.member },
  { key: "bilal", name: "Bilal Ahmed", email: "bilal@shi.local", role: "policyholder", password: PASSWORDS.member },
  { key: "zara", name: "Zara Iqbal", email: "zara@shi.local", role: "policyholder", password: PASSWORDS.member },
];

const daysAgo = (days) => new Date(Date.now() - days * 86_400_000);
const daysAhead = (days) => new Date(Date.now() + days * 86_400_000);

/** Writes a readable placeholder document so the "View" links actually resolve. */
const writeSeedDocument = (claim, documentType, body) => {
  if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
  }
  const slug = documentType.replace(/\s+/g, "-");
  const filename = `seed-${claim._id}-${slug}.txt`;
  fs.writeFileSync(path.join(uploadDir, filename), body, "utf8");
  return `/uploads/${filename}`;
};

const attachDocument = async (claim, documentType, summary) => {
  const fileUrl = writeSeedDocument(
    claim,
    documentType,
    [
      `SMART HEALTH INSURANCE - ${documentType.toUpperCase()}`,
      `Claim reference : ${claim._id}`,
      `Treatment       : ${claim.treatment}`,
      `Amount claimed  : $${claim.claimAmount.toLocaleString()}`,
      "",
      summary,
      "",
      "(Sample document generated by the demo seed script.)",
    ].join("\n")
  );

  return ClaimDocument.create({
    claimId: claim._id,
    documentType,
    fileUrl,
    uploadedAt: new Date(),
  });
};

const resetDemoData = async () => {
  console.log("Resetting existing data...");
  await Promise.all([
    Claim.deleteMany({}),
    ClaimDocument.deleteMany({}),
    FraudScore.deleteMany({}),
    ApprovalRecord.deleteMany({}),
    Notification.deleteMany({}),
    AuditLog.deleteMany({}),
    Policy.deleteMany({}),
    Hospital.deleteMany({}),
    User.deleteMany({ email: { $in: DEMO_USERS.map((u) => u.email) } }),
  ]);

  // Remove seed-generated upload placeholders, leaving real uploads alone.
  if (fs.existsSync(uploadDir)) {
    for (const file of fs.readdirSync(uploadDir)) {
      if (file.startsWith("seed-")) {
        fs.unlinkSync(path.join(uploadDir, file));
      }
    }
  }
};

/** Creates a user only if that email is free; returns the user either way. */
const ensureUser = async ({ name, email, role, password }) => {
  const existing = await User.findOne({ email });
  if (existing) {
    console.log(`  · user exists: ${email}`);
    return existing;
  }
  const user = await User.create({
    name,
    email,
    password: await bcrypt.hash(password, 10),
    role,
  });
  console.log(`  + user created: ${email} (${role})`);
  return user;
};

const ensureHospital = async (data) => {
  const existing = await Hospital.findOne({ registrationNumber: data.registrationNumber });
  if (existing) {
    console.log(`  · hospital exists: ${data.name}`);
    return existing;
  }
  const hospital = await Hospital.create(data);
  console.log(`  + hospital created: ${data.name}`);
  return hospital;
};

const ensurePolicy = async (data) => {
  const existing = await Policy.findOne({ policyNumber: data.policyNumber });
  if (existing) {
    console.log(`  · policy exists: ${data.policyNumber}`);
    return existing;
  }
  const policy = await Policy.create(data);
  console.log(`  + policy created: ${data.policyNumber}`);
  return policy;
};

const seed = async () => {
  await connectDB();

  if (RESET) {
    await resetDemoData();
  }

  // ---------------------------------------------------------------- users ---
  console.log("\nSeeding users...");
  const users = {};
  for (const spec of DEMO_USERS) {
    users[spec.key] = await ensureUser(spec);
  }

  // ------------------------------------------------------------ hospitals ---
  console.log("\nSeeding hospitals...");
  const cityGeneral = await ensureHospital({
    name: "City General Hospital",
    registrationNumber: "HOSP-100001",
    address: "12 Jinnah Avenue, Karachi",
    contact: "hospital@shi.local",
    isEligible: true,
  });

  // Deliberately suspended, to demonstrate the hospital-eligibility check.
  const northside = await ensureHospital({
    name: "Northside Clinic",
    registrationNumber: "HOSP-100002",
    address: "88 Northside Road, Lahore",
    contact: "contact@northside.local",
    isEligible: false,
  });

  const riverside = await ensureHospital({
    name: "Riverside Medical Center",
    registrationNumber: "HOSP-100003",
    address: "5 Riverside Drive, Islamabad",
    contact: "care@riverside.local",
    isEligible: true,
  });

  // Link the hospital staff account to its facility.
  if (String(users.hospitalStaff.hospitalId) !== String(cityGeneral._id)) {
    users.hospitalStaff.hospitalId = cityGeneral._id;
    await users.hospitalStaff.save();
    console.log("  + linked hospital staff account to City General Hospital");
  }

  // ------------------------------------------------------------- policies ---
  console.log("\nSeeding policies...");
  const ayeshaPolicy = await ensurePolicy({
    policyNumber: "POL-1001",
    policyholderId: users.ayesha._id,
    coverageLimit: 800000,
    coveredTreatments: [
      "MRI Scan",
      "Cardiology Consultation",
      "Appendectomy",
      "Physiotherapy",
    ],
    startDate: daysAgo(120),
    expiryDate: daysAhead(245),
    status: "active",
  });

  const bilalPolicy = await ensurePolicy({
    policyNumber: "POL-1002",
    policyholderId: users.bilal._id,
    coverageLimit: 200000,
    coveredTreatments: ["Dental Surgery", "General Checkup"],
    startDate: daysAgo(60),
    expiryDate: daysAhead(305),
    status: "active",
  });

  const zaraPolicy = await ensurePolicy({
    policyNumber: "POL-1003",
    policyholderId: users.zara._id,
    coverageLimit: 300000,
    coveredTreatments: ["General Checkup", "Vaccination", "Dermatology Consultation"],
    startDate: daysAgo(30),
    expiryDate: daysAhead(335),
    status: "active",
  });

  // --------------------------------------------------------------- claims ---
  // Every claim is created first, then scored, so the duplicate and
  // claim-frequency rules see the complete picture.
  console.log("\nSeeding claims...");

  const claimSpecs = [
    {
      label: "LOW risk (20), 7/7 validation",
      policyholderId: users.ayesha._id,
      hospitalId: cityGeneral._id,
      policyId: ayeshaPolicy._id,
      treatment: "MRI Scan",
      treatmentDate: daysAgo(18),
      claimAmount: 40000,
      description:
        "Routine MRI of the lumbar spine following reported lower back pain. No complications.",
      documents: [
        ["medical report", "Radiology findings: mild disc bulge at L4-L5. Conservative management advised."],
        ["hospital bill", "MRI suite 1 x $34,000. Consultant reporting fee $6,000. Total $40,000."],
      ],
    },
    {
      label: "HIGH risk (70), treatment not covered",
      policyholderId: users.ayesha._id,
      hospitalId: cityGeneral._id,
      policyId: ayeshaPolicy._id,
      treatment: "Cosmetic Rhinoplasty",
      treatmentDate: daysAgo(9),
      claimAmount: 600000,
      description:
        "Elective cosmetic procedure billed at a high proportion of the annual coverage limit.",
      documents: [
        ["medical report", "Elective cosmetic procedure. No clinical indication recorded."],
        ["hospital bill", "Theatre and surgeon fees $600,000."],
      ],
    },
    {
      label: "LOW risk (20), second valid claim",
      policyholderId: users.ayesha._id,
      hospitalId: cityGeneral._id,
      policyId: ayeshaPolicy._id,
      treatment: "Physiotherapy",
      treatmentDate: daysAgo(4),
      claimAmount: 25000,
      description: "Six physiotherapy sessions following the MRI findings.",
      documents: [
        ["medical report", "Six supervised physiotherapy sessions completed. Good progress."],
        ["hospital bill", "6 sessions x $4,166.67. Total $25,000."],
      ],
    },
    {
      // Passes every eligibility check yet still scores MEDIUM: a useful reminder
      // that validation and fraud scoring are independent axes.
      label: "MEDIUM risk (50), fully valid but high value",
      policyholderId: users.ayesha._id,
      hospitalId: cityGeneral._id,
      policyId: ayeshaPolicy._id,
      treatment: "Cardiology Consultation",
      treatmentDate: daysAgo(11),
      claimAmount: 570000,
      description:
        "Interventional cardiology admission. Covered by the policy, but a high-value claim from a frequent claimant.",
      documents: [
        ["medical report", "Angioplasty with single stent placement. Discharged day three, stable."],
        ["hospital bill", "Theatre $410,000. Stent $120,000. Ward and medication $40,000. Total $570,000."],
      ],
    },
    {
      label: "LOW risk (20) but 5/7 validation: suspended hospital, no bill",
      policyholderId: users.ayesha._id,
      hospitalId: northside._id,
      policyId: ayeshaPolicy._id,
      treatment: "Appendectomy",
      treatmentDate: daysAgo(30),
      claimAmount: 90000,
      description:
        "Submitted by a facility whose empanelment is currently suspended, with no hospital bill attached.",
      documents: [["medical report", "Laparoscopic appendectomy performed without complication."]],
    },
    // Three near-identical high-value claims plus a fourth, which together
    // trigger the duplicate and multiple-recent-claims rules.
    {
      label: "HIGH risk (80), duplicate cluster 1/3",
      policyholderId: users.bilal._id,
      hospitalId: cityGeneral._id,
      policyId: bilalPolicy._id,
      treatment: "Dental Surgery",
      treatmentDate: daysAgo(20),
      claimAmount: 150000,
      description: "Full-mouth restorative dental surgery.",
      documents: [
        ["medical report", "Full-mouth restorative work. Six units placed."],
        ["hospital bill", "Restorative dental surgery $150,000."],
      ],
    },
    {
      label: "HIGH risk (80), duplicate cluster 2/3",
      policyholderId: users.bilal._id,
      hospitalId: cityGeneral._id,
      policyId: bilalPolicy._id,
      treatment: "Dental Surgery",
      treatmentDate: daysAgo(13),
      claimAmount: 150000,
      description: "Repeat submission for full-mouth restorative dental surgery.",
      documents: [
        ["medical report", "Full-mouth restorative work. Six units placed."],
        ["hospital bill", "Restorative dental surgery $150,000."],
      ],
    },
    {
      label: "HIGH risk (80), duplicate cluster 3/3",
      policyholderId: users.bilal._id,
      hospitalId: cityGeneral._id,
      policyId: bilalPolicy._id,
      treatment: "Dental Surgery",
      treatmentDate: daysAgo(6),
      claimAmount: 150000,
      description: "Third identical submission within a single month.",
      documents: [
        ["medical report", "Full-mouth restorative work. Six units placed."],
        ["hospital bill", "Restorative dental surgery $150,000."],
      ],
    },
    {
      label: "LOW risk (20), frequent claimant",
      policyholderId: users.bilal._id,
      hospitalId: cityGeneral._id,
      policyId: bilalPolicy._id,
      treatment: "General Checkup",
      treatmentDate: daysAgo(2),
      claimAmount: 5000,
      description: "Annual general health checkup.",
      documents: [
        ["medical report", "Annual checkup. All observations within normal range."],
        ["hospital bill", "Consultation and basic panel $5,000."],
      ],
    },
    {
      // Only claim on its policy, at a quiet facility: nothing fires at all.
      label: "ZERO risk (0), pristine claim",
      policyholderId: users.zara._id,
      hospitalId: riverside._id,
      policyId: zaraPolicy._id,
      treatment: "Dermatology Consultation",
      treatmentDate: daysAgo(7),
      claimAmount: 18000,
      description: "Single dermatology consultation for a treated skin allergy.",
      documents: [
        ["medical report", "Contact dermatitis diagnosed. Topical treatment prescribed, review in six weeks."],
        ["hospital bill", "Specialist consultation $15,000. Dispensed medication $3,000. Total $18,000."],
      ],
    },
  ];

  const created = [];
  for (const spec of claimSpecs) {
    const claim = await Claim.create({
      policyholderId: spec.policyholderId,
      hospitalId: spec.hospitalId,
      policyId: spec.policyId,
      treatment: spec.treatment,
      treatmentDate: spec.treatmentDate,
      claimAmount: spec.claimAmount,
      description: spec.description,
      status: "pending",
      submittedAt: spec.treatmentDate,
    });

    for (const [documentType, summary] of spec.documents) {
      await attachDocument(claim, documentType, summary);
    }

    await notifyUser({
      userId: spec.policyholderId,
      claimId: claim._id,
      message: "Your claim has been submitted.",
    });

    await createAuditLog({
      userId: users.hospitalStaff._id,
      action: `Hospital submitted Claim ${claim._id}`,
      claimId: claim._id,
    });

    created.push({ claim, label: spec.label });
    console.log(`  + claim created: ${spec.treatment} — ${spec.label}`);
  }

  // ------------------------------------------- validation + fraud scoring ---
  console.log("\nRunning validation and fraud scoring...");
  for (const entry of created) {
    const { fraudScore, validationResults } = await processSubmittedClaim(
      entry.claim,
      users.hospitalStaff._id
    );
    const passed = validationResults.checks.filter((c) => c.passed).length;
    console.log(
      `  · ${entry.claim.treatment.padEnd(22)} risk ${String(fraudScore.score).padStart(3)}/100 ` +
        `(${fraudScore.riskLevel.padEnd(6)})  validation ${passed}/${validationResults.checks.length}`
    );
  }

  // ---------------------------------------------------- officer decisions ---
  // A few decisions so the dashboards are not entirely "pending" on first load.
  console.log("\nRecording officer decisions...");
  const decide = async (claim, decision, remarks) => {
    claim.status = decision;
    await claim.save();

    await ApprovalRecord.create({
      claimId: claim._id,
      officerId: users.officer._id,
      decision,
      remarks,
      decidedAt: new Date(),
    });

    const messages = {
      approved: "Your claim has been approved.",
      rejected: "Your claim has been rejected.",
      more_information_required: "Additional information is required.",
    };
    await notifyUser({
      userId: claim.policyholderId,
      claimId: claim._id,
      message: messages[decision],
    });

    const labels = {
      approved: "Officer approved",
      rejected: "Officer rejected",
      more_information_required: "Officer requested additional information for",
    };
    await createAuditLog({
      userId: users.officer._id,
      action: `${labels[decision]} Claim ${claim._id}`,
      claimId: claim._id,
    });

    console.log(`  + ${decision}: ${claim.treatment}`);
  };

  const byTreatment = (name) => created.find((c) => c.claim.treatment === name)?.claim;

  const mri = byTreatment("MRI Scan");
  if (mri) {
    await decide(mri, "approved", "All eligibility checks passed and risk score is low. Approved for payout.");
  }

  const rhinoplasty = byTreatment("Cosmetic Rhinoplasty");
  if (rhinoplasty) {
    await decide(
      rhinoplasty,
      "rejected",
      "Treatment is not listed on the policy and the amount approaches the annual coverage limit."
    );
  }

  const appendectomy = byTreatment("Appendectomy");
  if (appendectomy) {
    await decide(
      appendectomy,
      "more_information_required",
      "Submitting facility is suspended and the hospital bill is missing. Please resubmit with both."
    );
  }

  // --------------------------------------------------------------- report ---
  console.log("\n" + "=".repeat(62));
  console.log("Demo data ready. Sign in with any of these accounts:");
  console.log("=".repeat(62));
  for (const u of DEMO_USERS) {
    console.log(`  ${u.role.padEnd(13)} ${u.email.padEnd(22)} ${u.password}`);
  }
  console.log("=".repeat(62));
  console.log("Tip: re-run with `npm run seed:demo -- --reset` for a clean slate.\n");

  await mongoose.connection.close();
  process.exit(0);
};

seed().catch(async (error) => {
  console.error("Failed to seed demo data:", error);
  await mongoose.connection.close().catch(() => {});
  process.exit(1);
});
